-- ============================================================================
-- V1__baseline.sql
-- Core schema: sources, articles, authors, tags, crawl jobs, users, bookmarks.
--
-- Conventions used throughout:
--   * TIMESTAMPTZ everywhere. Never TIMESTAMP. Crawling foreign sources means
--     you WILL get mixed offsets; store UTC instants, format at the edge.
--   * Enum-like columns are TEXT + CHECK, not native ENUM types. Native enums
--     can only be extended (ALTER TYPE ADD VALUE), never reordered or shrunk,
--     and that statement has transactional caveats -- which fights Flyway.
--     TEXT + CHECK maps cleanly to Hibernate's @Enumerated(EnumType.STRING).
--   * IDENTITY columns, not SERIAL. SERIAL is legacy (owns a sequence via an
--     implicit dependency); IDENTITY is the SQL standard. BY DEFAULT (not
--     ALWAYS) so tests and seed scripts can insert explicit ids.
--   * Every FK is indexed. Postgres does NOT auto-index FK columns -- only the
--     referenced side (via the PK). Unindexed FKs make parent deletes do a
--     seq scan on every child table.
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;   -- digest() for content/url hashing
CREATE EXTENSION IF NOT EXISTS citext;     -- case-insensitive email


-- ---------------------------------------------------------------------------
-- updated_at trigger helper
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- ---------------------------------------------------------------------------
-- source: one row per feed / site we ingest from.
-- Crawl policy lives in the DB, not in application config, so the admin UI can
-- tune it without a redeploy.
-- ---------------------------------------------------------------------------
CREATE TABLE source (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug                  TEXT        NOT NULL,
    name                  TEXT        NOT NULL,
    homepage_url          TEXT        NOT NULL,
    feed_url              TEXT,
    kind                  TEXT        NOT NULL,
    language              CHAR(2),

    -- crawl policy
    enabled               BOOLEAN     NOT NULL DEFAULT TRUE,
    crawl_interval_sec    INTEGER     NOT NULL DEFAULT 900,
    rate_limit_per_min    INTEGER     NOT NULL DEFAULT 20,
    next_crawl_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_crawled_at       TIMESTAMPTZ,
    consecutive_failures  INTEGER     NOT NULL DEFAULT 0,

    -- HTTP conditional GET state: lets re-crawls return 304 instead of a body.
    -- Cheap to implement, and it's the single most polite thing a crawler does.
    http_etag             TEXT,
    http_last_modified    TEXT,

    -- CSS selectors / API params for kind='html' or 'api'. JSONB because the
    -- shape genuinely varies per source -- this is the one place schemaless
    -- earns its keep.
    config                JSONB       NOT NULL DEFAULT '{}'::jsonb,

    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT source_slug_uk        UNIQUE (slug),
    CONSTRAINT source_kind_ck        CHECK (kind IN ('rss', 'atom', 'html', 'api')),
    CONSTRAINT source_interval_ck    CHECK (crawl_interval_sec >= 60),
    CONSTRAINT source_rate_ck        CHECK (rate_limit_per_min > 0),
    -- a feed-type source must actually have a feed url
    CONSTRAINT source_feed_url_ck    CHECK (kind NOT IN ('rss','atom') OR feed_url IS NOT NULL)
);

CREATE TRIGGER source_set_updated_at
    BEFORE UPDATE ON source
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- The scheduler's hot query: "which sources are due?"
CREATE INDEX source_due_idx ON source (next_crawl_at) WHERE enabled;


-- ---------------------------------------------------------------------------
-- author
-- ---------------------------------------------------------------------------
CREATE TABLE author (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id     BIGINT      NOT NULL REFERENCES source (id) ON DELETE CASCADE,
    name          TEXT        NOT NULL,
    external_id   TEXT,
    profile_url   TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- same human name on two different sites = two rows. Cross-source identity
    -- resolution is a different (much harder) problem; don't pretend to solve it.
    CONSTRAINT author_source_name_uk UNIQUE (source_id, name)
);


-- ---------------------------------------------------------------------------
-- article: the narrow "feed row". Deliberately does NOT contain body text.
--
-- The feed query scans this table hard. Keeping it narrow means more rows per
-- 8KB page, which means fewer page reads per scan. Body text lives in
-- article_content, one join away, fetched only when someone opens the reader.
-- ---------------------------------------------------------------------------
CREATE TABLE article (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id       BIGINT      NOT NULL REFERENCES source (id) ON DELETE CASCADE,
    author_id       BIGINT               REFERENCES author (id) ON DELETE SET NULL,

    canonical_url   TEXT        NOT NULL,

    -- Do NOT put a UNIQUE index directly on canonical_url. A btree index tuple
    -- is capped at ~2704 bytes; a pathological URL (tracking params, data URIs)
    -- will blow up an INSERT at 3am. Hash to a fixed 32 bytes and make THAT the
    -- key. STORED generated column = the DB guarantees it, not the app.
    url_hash        BYTEA       NOT NULL
                    GENERATED ALWAYS AS (digest(canonical_url, 'sha256')) STORED,

    title           TEXT        NOT NULL,
    summary         TEXT,
    image_url       TEXT,
    language        CHAR(2),
    word_count      INTEGER,

    -- exact-dup detection: sha256 of normalised body text
    content_hash    BYTEA,
    -- near-dup detection: 64-bit simhash. Syndicated articles (VnExpress ->
    -- aggregator -> aggregator) differ by a byline but should collapse.
    simhash         BIGINT,
    duplicate_of_id BIGINT               REFERENCES article (id) ON DELETE SET NULL,

    status          TEXT        NOT NULL DEFAULT 'discovered',

    published_at    TIMESTAMPTZ NOT NULL,
    discovered_at   TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- @Version for optimistic locking. Two enrichment consumers (summariser,
    -- tagger) will race on the same row; this makes the loser retry instead of
    -- silently clobbering.
    version         INTEGER     NOT NULL DEFAULT 0,

    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT article_url_hash_uk   UNIQUE (url_hash),
    CONSTRAINT article_status_ck     CHECK (status IN (
        'discovered', 'fetching', 'extracted', 'published', 'failed', 'duplicate')),
    CONSTRAINT article_word_count_ck CHECK (word_count IS NULL OR word_count >= 0),
    CONSTRAINT article_not_self_dup  CHECK (duplicate_of_id IS DISTINCT FROM id),
    -- if it's marked duplicate, it must point at the original
    CONSTRAINT article_dup_ck        CHECK (status <> 'duplicate' OR duplicate_of_id IS NOT NULL)
);

CREATE TRIGGER article_set_updated_at
    BEFORE UPDATE ON article
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- === The index that makes the whole app fast ================================
-- The main feed uses keyset (cursor) pagination:
--
--   SELECT ... FROM article
--    WHERE status = 'published'
--      AND (published_at, id) < ($cursor_ts, $cursor_id)
--    ORDER BY published_at DESC, id DESC
--    LIMIT 30;
--
-- Column order matches ORDER BY exactly, so Postgres walks the index backwards
-- and stops after 30 tuples -- no sort node, no growing OFFSET cost. The
-- partial WHERE keeps failed/duplicate rows out of the index entirely.
-- `id` is in the key to break ties: without it, two articles sharing a
-- published_at timestamp can be skipped or repeated across page boundaries.
CREATE INDEX article_feed_idx
    ON article (published_at DESC, id DESC)
    WHERE status = 'published';

-- per-source feed, same shape
CREATE INDEX article_source_feed_idx
    ON article (source_id, published_at DESC, id DESC)
    WHERE status = 'published';

-- FK index (see header note)
CREATE INDEX article_author_idx ON article (author_id) WHERE author_id IS NOT NULL;

-- dedup lookup: "have we seen this exact body under another URL?"
CREATE INDEX article_content_hash_idx ON article (content_hash) WHERE content_hash IS NOT NULL;

-- crawler backlog: rows discovered but not yet enriched
CREATE INDEX article_pending_idx ON article (discovered_at)
    WHERE status IN ('discovered', 'fetching');


-- ---------------------------------------------------------------------------
-- article_content: the wide side. 1:1 with article.
--
-- Postgres would TOAST these columns out-of-line anyway once they exceed ~2KB,
-- so the split is partly belt-and-braces -- but it also means a SELECT * from a
-- careless JPA mapping can't accidentally drag 50KB of HTML into the feed
-- response. Structural guarantee > code review.
-- ---------------------------------------------------------------------------
CREATE TABLE article_content (
    article_id    BIGINT      PRIMARY KEY REFERENCES article (id) ON DELETE CASCADE,
    html          TEXT,
    text_plain    TEXT        NOT NULL,
    extracted_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    extractor     TEXT        NOT NULL DEFAULT 'jsoup-readability'
);


-- ---------------------------------------------------------------------------
-- tag / article_tag
-- ---------------------------------------------------------------------------
CREATE TABLE tag (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug        TEXT        NOT NULL,
    label       TEXT        NOT NULL,
    kind        TEXT        NOT NULL DEFAULT 'topic',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT tag_slug_uk UNIQUE (slug),
    CONSTRAINT tag_kind_ck CHECK (kind IN ('topic', 'tech', 'company', 'manual'))
);

CREATE TABLE article_tag (
    article_id  BIGINT      NOT NULL REFERENCES article (id) ON DELETE CASCADE,
    tag_id      BIGINT      NOT NULL REFERENCES tag (id)     ON DELETE CASCADE,
    assigned_by TEXT        NOT NULL DEFAULT 'llm',
    confidence  REAL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (article_id, tag_id),
    CONSTRAINT article_tag_by_ck   CHECK (assigned_by IN ('llm', 'rule', 'manual', 'source')),
    CONSTRAINT article_tag_conf_ck CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1))
);

-- The PK covers (article_id, tag_id) -- good for "tags of this article".
-- The reverse direction ("articles with this tag") needs its own index; a
-- composite PK is only usable for a leading-column lookup.
CREATE INDEX article_tag_reverse_idx ON article_tag (tag_id, article_id);


-- ---------------------------------------------------------------------------
-- crawl_job: durable work queue.
--
-- Yes, Redis/BullMQ or Kafka can do this. The DB table is here on purpose:
-- it gives transactional enqueue (job + article rows commit together, so you
-- can never enqueue work for a row that rolled back), it survives a Redis
-- flush, and it's queryable by the admin UI. Kafka comes in at Phase 4 for
-- fan-out of `article.discovered`, which is a different job.
-- ---------------------------------------------------------------------------
CREATE TABLE crawl_job (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id      BIGINT      NOT NULL REFERENCES source (id) ON DELETE CASCADE,
    job_type       TEXT        NOT NULL DEFAULT 'fetch_feed',
    state          TEXT        NOT NULL DEFAULT 'pending',

    attempt        INTEGER     NOT NULL DEFAULT 0,
    max_attempts   INTEGER     NOT NULL DEFAULT 5,

    scheduled_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    started_at     TIMESTAMPTZ,
    finished_at    TIMESTAMPTZ,

    -- who holds the lease, and until when. Lets a reaper resurrect jobs whose
    -- worker was OOM-killed mid-run instead of leaving them 'running' forever.
    locked_by      TEXT,
    locked_until   TIMESTAMPTZ,

    last_error     TEXT,
    payload        JSONB       NOT NULL DEFAULT '{}'::jsonb,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT crawl_job_type_ck  CHECK (job_type IN ('fetch_feed', 'fetch_article', 'extract', 'enrich')),
    CONSTRAINT crawl_job_state_ck CHECK (state IN ('pending', 'running', 'succeeded', 'failed', 'dead')),
    CONSTRAINT crawl_job_att_ck   CHECK (attempt >= 0 AND attempt <= max_attempts)
);

-- Claim query (worker side):
--
--   UPDATE crawl_job SET state='running', locked_by=:worker,
--          locked_until = now() + interval '5 minutes',
--          started_at = now(), attempt = attempt + 1
--    WHERE id IN (
--        SELECT id FROM crawl_job
--         WHERE state = 'pending' AND scheduled_at <= now()
--         ORDER BY scheduled_at
--         LIMIT 10
--         FOR UPDATE SKIP LOCKED     -- <-- N workers, zero contention
--    )
--   RETURNING *;
--
-- SKIP LOCKED is the whole trick: each worker steps over rows another worker
-- has already locked instead of blocking behind them.
CREATE INDEX crawl_job_claim_idx ON crawl_job (scheduled_at)
    WHERE state = 'pending';

-- reaper: find leases that expired
CREATE INDEX crawl_job_stale_idx ON crawl_job (locked_until) WHERE state = 'running';

-- Don't let the scheduler pile up 400 pending jobs for one source because the
-- site was down for an hour. Partial unique index = "at most one live job per
-- source per type", enforced by the DB rather than hoped for in a service.
CREATE UNIQUE INDEX crawl_job_live_uk ON crawl_job (source_id, job_type)
    WHERE state IN ('pending', 'running');

CREATE INDEX crawl_job_source_idx ON crawl_job (source_id, created_at DESC);


-- ---------------------------------------------------------------------------
-- crawl_log: one row per HTTP attempt. Append-only, high volume.
-- This is what the admin dashboard graphs, and what tells you a source quietly
-- started returning 403 two days ago.
-- ---------------------------------------------------------------------------
CREATE TABLE crawl_log (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id        BIGINT      REFERENCES crawl_job (id) ON DELETE SET NULL,
    source_id     BIGINT      NOT NULL REFERENCES source (id) ON DELETE CASCADE,
    http_status   INTEGER,
    bytes         INTEGER,
    duration_ms   INTEGER,
    items_found   INTEGER,
    items_new     INTEGER,
    error         TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX crawl_log_source_time_idx ON crawl_log (source_id, created_at DESC);
CREATE INDEX crawl_log_job_idx ON crawl_log (job_id) WHERE job_id IS NOT NULL;


-- ---------------------------------------------------------------------------
-- app_user  ("user" is a reserved word in Postgres -- don't fight it)
-- ---------------------------------------------------------------------------
CREATE TABLE app_user (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email          CITEXT      NOT NULL,
    password_hash  TEXT,                      -- null for OAuth-only accounts
    google_sub     TEXT,
    display_name   TEXT        NOT NULL,
    avatar_url     TEXT,
    role           TEXT        NOT NULL DEFAULT 'USER',
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT app_user_email_uk  UNIQUE (email),        -- CITEXT => case-insensitive
    CONSTRAINT app_user_google_uk UNIQUE (google_sub),
    CONSTRAINT app_user_role_ck   CHECK (role IN ('USER', 'ADMIN')),
    CONSTRAINT app_user_auth_ck   CHECK (password_hash IS NOT NULL OR google_sub IS NOT NULL)
);

CREATE TRIGGER app_user_set_updated_at
    BEFORE UPDATE ON app_user
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ---------------------------------------------------------------------------
-- refresh_token: rotating refresh tokens.
-- Store a hash, never the token itself -- a DB dump must not be a session
-- hijack kit. `replaced_by_id` gives you a rotation chain, so replay of an old
-- token is detectable (and should nuke the whole family).
-- ---------------------------------------------------------------------------
CREATE TABLE refresh_token (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT      NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    token_hash     BYTEA       NOT NULL,
    issued_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at     TIMESTAMPTZ NOT NULL,
    revoked_at     TIMESTAMPTZ,
    replaced_by_id BIGINT      REFERENCES refresh_token (id) ON DELETE SET NULL,
    user_agent     TEXT,
    ip             INET,

    CONSTRAINT refresh_token_hash_uk UNIQUE (token_hash)
);

CREATE INDEX refresh_token_user_idx ON refresh_token (user_id) WHERE revoked_at IS NULL;


-- ---------------------------------------------------------------------------
-- bookmark
-- ---------------------------------------------------------------------------
CREATE TABLE bookmark (
    user_id     BIGINT      NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    article_id  BIGINT      NOT NULL REFERENCES article (id)  ON DELETE CASCADE,
    note        TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (user_id, article_id)
);

-- "my bookmarks, newest first" -- keyset again
CREATE INDEX bookmark_user_recent_idx ON bookmark (user_id, created_at DESC);
